version: '3'
services:
  mongodb:
    image: mongo
    container_name: book-box
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_DATABASE: book-box-dev
